#!/usr/bin/env bash
# setting up nginx on server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart

