#!/usr/bin/env bash
# redirect permanently

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School for the win!" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
new="\        rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "/server_name _/a $new\n" /etc/nginx/sites-available/default
sudo service nginx restart
error_msg="error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /usr/share/nginx/html;\ninternal;\n}"
sudo sed -i "s/location / {/$error_msg/" /etc/nginx/sites-available/default
sudo service nginx restart
