#!/usr/bin/env bash
# redirect permanently

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Holberton School" > /var/www/html/index.nginx-debian.html
sudo service nginx restart
sudo printf "server {
listen 80;
listen [::]:80;
server_name _;
rewrite ^/redirect_me/ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
root /var/www/html;
index.html index index.nginx-debian.html;
error_page 404 /custom_404.html;
location = /custom_404.html {
root /usr/share/nginx/html;
internal;
}
}\n"
sudo service nginx restart
