#!/usr/bin/env bash
#handling many SIGN

echo "$$" > "/var/run/holbertonscript.pid"

while ((1 == 1))
do 
   echo "To infinity and beyond"
   trap "echo I hate the kill command & rm -f /var/run/holbertonscript.pid & exit 0" 15
   trap "echo Y U no love me?! & exit 0" 2
   trap "rm -f /var/run/holbertonscript.pid & exit 0" 3
   sleep 2
done
