#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times

let c=0
while ((c<10))
do
    echo "Holberton School"
    if ((c==8))
          then
	      echo "Hi"
    fi
    ((c++))
done
